apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: react-ingress-gateway
spec:
  listeners:
    - port: 80
      protocol: http
      services:
        - name: web
          hosts: ["*"]
