---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: public-api
---
apiVersion: v1
kind: Service
metadata:
  name: public-api
spec:
  selector:
    app: public-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api
spec:
  replicas: 2
  selector:
    matchLabels:
      service: public-api
      app: public-api
  template:
    metadata:
      labels:
        service: public-api
        app: public-api
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "product-api.product:9090:azure-west-us-2,payments-api.default:9091:aws-us-east-1,jaeger-http-collector.default:14268:aws-us-east-1,zipkin-http-collector.default:9411:aws-us-east-1"
    spec:
      serviceAccountName: public-api
      containers:
        - name: public-api
          image: hashicorpdemoapp/public-api:v0.0.7
          ports:
            - containerPort: 8080
          env:
            - name: BIND_ADDRESS
              value: ":8080"
            - name: PRODUCTS_API_URI
              value: "http://localhost:9090"
            - name: PAYMENT_API_URI
              value: "http://localhost:9091"
            - name: JAEGER_ENDPOINT
              value: http://127.0.0.1:14268/api/traces
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 2
